apps/book_reviewer/urls.py
from django.conf.urls import url
from . import views          
  
urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^editor$', views.show_editor, name='editor'),
  url(r'^add_book$', views.add_book_and_review, name='add_book'),
  url(r'^show_book/(?P<id>\d+)$', views.show_book, name='show_book'),
  url(r'^add_review/(?P<id>\d+)$', views.add_review, name='add_review'),
  url(r'^destroy/(?P<review_id>\d+)/(?P<book_id>\d+)$', views.destroy, name='destroy'),
  url(r'^show_user/(?P<id>\d+)$', views.show_user, name='show_user'),
  url(r'^logout$', views.logout, name='logout'),
]

apps/login/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login_reg$', views.login_reg, name='login_reg'),
]

belt_reviewer/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login.urls',namespace='login')),
    url(r'^book/', include('apps.book_reviewer.urls', namespace='book')),
]

apps/book_reviewer/models.py
from __future__ import unicode_literals
from ..login.models import User
from django.db import models

class BookManager(models.Manager):
    def add_book(self, request):
        errors = []

        if request.POST['author_name'] == "" and request.POST['new_author_name'] == "":
            errors.append('Please select or enter an author.')
            return (False, errors)
        elif request.POST['author_name'] == "":
            author = Author.objects.create(name=request.POST['new_author_name'])
        else:
            author = Author.objects.get(id=request.POST['author_name'])

        new_book = Book.objects.create(title=request.POST['title'], author=author)
        return (True, new_book)

class ReviewManager(models.Manager):
    def add_review(self, request, new_book_id):
        book = Book.objects.get(id=new_book_id)
        reviewer = User.objects.get(id=request.session['user']['user_id'])
        review = Review.objects.create(content=request.POST['review'], creator=reviewer, reviewed_book=book, rating=request.POST['rating'])

    def destroy(self, request, id):
        Review.objects.get(id=id).delete()


class Author(models.Model):
    name = models.CharField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, related_name='books')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BookManager()

class Review(models.Model):
    content = models.CharField(max_length=255)
    creator = models.ForeignKey(User, related_name='reviews')
    reviewed_book = models.ForeignKey(Book, related_name='books_reviews')
    rating = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ReviewManager()

apps/login/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
import bcrypt, re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def validate_reg(self, request):
        errors = self.validate_inputs(request)

        if errors:
            return (False, errors)

        pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())

        user = self.create(name=request.POST['name'], alias=request.POST['alias'], email=request.POST['email'], password=pw_hash)

        return (True, user)

    def validate_login(self, request):
        try:
            user = User.objects.get(email=request.POST['email'])
            password = request.POST['password'].encode()
            if bcrypt.hashpw(password, user.password.encode()):
                return (True, user)

        except ObjectDoesNotExist:
            pass

        return (False, ["Invalid login."])

    def validate_inputs(self, request):
        errors = []

        if not request.POST['name']:
            errors.append('Name cannot be blank.')
        if not request.POST['email']:
            errors.append('Please enter an email.')
        elif not EMAIL_REGEX.match(request.POST['email']):
            errors.append('Invalid email.')
        if len(request.POST['password']) < 8:
            errors.append('Password must be at least 8 characters.')
        if request.POST['password'] != request.POST['confirm']:
            errors.append('Password and password confirm must match.')

        return errors

class User(models.Model):
    name = models.CharField(max_length = 50)
    alias = models.CharField(max_length = 50)
    email = models.CharField(max_length = 50)
    password = models.CharField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

apps/book_reviewer/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from models import Book, Review, Author, User

def index(request):
    if session_check(request):
        context = {
            'recent_reviews': Review.objects.order_by('-created_at')[:3],
            'all_books': Book.objects.all()
        }
        return render(request, "book_reviewer/index.html", context)

    return redirect('login:index')

def show_editor(request):
    if session_check(request):
        context = {
            'authors': Author.objects.all()
        }

        return render(request, 'book_reviewer/add.html', context)

    return redirect('login:index')

def add_book_and_review(request):
    if session_check(request):
        result = Book.objects.add_book(request)
        if result[0]==False:
            print_errors(request, result[1])
            return redirect('book:editor')

        Review.objects.add_review(request, result[1].id)

        return redirect('book:show_book', result[1].id)

    return redirect('login:index')

def print_errors(request, error_list):
    for error in error_list:
        messages.add_message(request, messages.INFO, error)

def add_review(request, id):
    Review.objects.add_review(request, id)

    return redirect('book:show_book', id)

def show_book(request, id):
    if session_check(request):
        context = {
            'book': Book.objects.get(id=id),
            'reviews': Review.objects.filter(reviewed_book=id)
        }

        return render(request, 'book_reviewer/show_book.html', context)

    return redirect('login:index')

def show_user(request, id):
    if session_check(request):
        context = {
            'user': User.objects.get(id=id),
            'reviewed_books': Book.objects.filter(books_reviews__creator__id=id)
        }
        return render(request, 'book_reviewer/show_user.html', context)

    return redirect('login:index')

def destroy(request, review_id, book_id):
    if session_check(request):
        Review.objects.destroy(request, review_id)

        return redirect('book:show_book', book_id)

    return redirect('login:index')

def logout(request):
    request.session.clear()

    return redirect('login:index')

def session_check(request):
    if 'user' in request.session:
        return True
    else:
        return False

apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from models import User

def session_check(request):
    if 'user' in request.session:
        return True
    else:
        return False

def index(request):
    if session_check(request):
        # VV REDIRECT TO APP VV
        return redirect('book:index')
    else:
        return render(request,'login/index.html')

def login_reg(request):
    if request.POST['action'] == 'register':
        result = User.objects.validate_reg(request)

    elif request.POST['action'] == 'login':
        result = User.objects.validate_login(request)

    if result[0] == False:
        print_errors(request, result[1])
        return redirect('login:index')

    return log_user_in(request, result[1])

def print_errors(request, error_list):
    for error in error_list:
        messages.add_message(request, messages.INFO, error)

def log_user_in(request, user):
    request.session['user'] = {
        'user_id': user.id,
        'name': user.name
    }

    # VV REDIRECT TO APP VV
    return redirect('book:index')

apps/book_reviewer/templates/book_reviewer/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add books</title>
  </head>
  <body>
    <a href="{% url 'book:index' %}">Home</a>
    <a href="{% url 'book:logout' %}">Logout</a>
    <h3>Add a New Book Title and a Review</h3>
    <form action="{% url 'book:add_book' %}" method="post">
    {% csrf_token %}
    <p>Book Title: <input type="text" name="title"></p>
      <p>Author:</p>
      <p>Choose from the list:<select name="author_name">
        <option value="">-----</option>
        {% for author in authors %}
        <option value="{{ author.id }}">{{ author.name }}</option>
        {% endfor %}
      </select></p>
      <p>Or add a new author: <input type="text" name="new_author_name"></p>
      {% if messages %}
        {% for message in messages %}
            <h5>{{ message }}</h5>
        {% endfor %}
      {% endif %}
      <p>Review: <textarea name="review" rows="8" cols="40"></textarea></p>
      <p>Rating: <select name="rating">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select></p>
      <input type="submit" name="submit" value="Add Book and Review">
    </form>
  </body>
</html>

apps/book_reviewer/templates/book_reviewer/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Review</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'book_reviewer/book.css' %}">
</head>
<body>
    <h3>Welcome, {{ request.session.user.name }}</h3>
    <a href="{% url 'book:editor' %}">Add Book and Review</a>
    <a href="{% url 'book:logout' %}">Logout</a>
    <h2>Recent Book Reviews:</h2>
    {% for review in recent_reviews %}
    <h4><a href="{% url 'book:show_book' review.reviewed_book.id %}">{{ review.reviewed_book.title }}</a></h4>
    <img src="{% static 'book_reviewer/' %}{{review.rating}}.svg" alt="Rating: {{ review.rating }}"/>
    <a href="{% url 'book:show_user' review.creator.id %}">{{ review.creator.name }}</a><p>
      {{ review.content }}
    </p>
    <p>{{ review.created_at }}</p>
    <br>
    {% endfor %}
    <h2>Other Books with Reviews:</h2>
    <ul>
        {% for book in all_books %}
      <li><a href="{% url 'book:show_book' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

apps/book_reviewer/templates/book_reviewer/show_book.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ book.title }}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'book_reviewer/book.css' %}">
</head>

<body>
    <h1>{{ book.title }}</h1>
    <h2>{{ book.author.name }}</h2>
    <a href="{% url 'book:index' %}">Home</a>
    <a href="{% url 'book:logout' %}">Logout</a>
    <h2>Reviews:</h2>
    {% for review in reviews %}
        <img src="{% static 'book_reviewer/' %}{{review.rating}}.svg" alt="Rating: {{ review.rating }}"/>
        <a href="{% url 'book:show_user' review.creator.id %}">{{ review.creator.name }}</a>
        <p> {{ review.content }}</p>
        {% if review.creator.id == request.session.user.user_id %}
        <a href="{% url 'book:destroy' review_id=review.id book_id=book.id  %}">Delete</a>
        {% endif %}
        <p>{{ review.created_at }}</p>
    {% endfor %}
    <form action="{% url 'book:add_review' book.id %}" method="POST">
        {% csrf_token %}
        <p>Review:</p>
        <textarea name="review" rows="8" cols="40"></textarea>
        <p>Rating:
            <select name="rating">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </p>
        <input type="submit" name="submit" value="Add Review">
    </form>
</body>

</html>

apps/book_reviewer/templates/book_reviewer/show_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.name }}</title>
</head>
<body>
    <a href="{% url 'book:index' %}">Home</a>
    <a href="{% url 'book:editor' %}">Add Book and Review</a>
    <a href="{% url 'book:logout' %}">Logout</a>
    <h2>User Alias: {{ user.alias }}</h2>
    <h4>Name: {{ user.name }}</h4>
    <h4>Email: {{ user.email }}</h4>
    <h4>Total Reviews: {{ user.reviews.count }}</h4>

    <h3>{{ user.name }}'s Reviews</h3>
    {% for book in reviewed_books %}
    <a href="{% url 'book:show_book' book.id %}">{{ book.title }}</a>
    {% endfor %}

</body>
</html>

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Login</title>
    {% load static %}
</head>

<body>
    <div id="wrapper">
        <h2>Log In</h2>
        <form action="login_reg" method="post">
            {% csrf_token %}
            <p>Email: <input type="text" name="email"></p>
            <p>Password: <input type="password" name="password"></p>
            <input type="hidden" name="action" value="login">
            <input type="submit" name="submit" value="submit">
        </form><!-- Login -->
        <h2>Register</h2>
        <form action="login_reg" method="post">
            {% csrf_token %}
            <p>Name: <input type="text" name="name"></p>
            <p>Alias: <input type="text" name="alias"></p>
            <p>Email: <input type="text" name="email"></p>
            <p>Password: <input type="password" name="password"></p>
            <p>Confirm Password: <input type="password" name="confirm"></p>
            <input type="hidden" name="action" value="register">
            <input type="submit" name="submit" value="submit">
        </form><!-- Registration -->
        {% if messages %}
            {% for message in messages %}
                <h5>{{ message }}</h5>
            {% endfor %}
        {% endif %}
    </div><!--  /#wrapper -->
</body>

</html>

apps/login/templates/login/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>it worked</h1>
</body>
</html>